sudo: required
services: 
  - docker
before_install:
  - docker build -t kcoddington/react-test -f ./client/Dockerfile.dev
script:
  - docker run -e CI=true kcoddington/react-test npm test
after_success:
  - docker build -t kcoddington/multi-client ./client
  - docker build -t kcoddington/multi-nginx ./nginx
  - docker build -t kcoddington/multi-server ./server
  - docker build -t kcoddington/multi-worker ./worker
  # Login to the docker CLI

  # Take those images and push them to Docker Hub