sudo: required
services: 
  - docker
before_install:
  - docker build -t kcoddington/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true kcoddington/react-test npm test
after_success:
  - docker build -t kcoddington/multi-client ./client
  - docker build -t kcoddington/multi-nginx ./nginx
  - docker build -t kcoddington/multi-server ./server
  - docker build -t kcoddington/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push kcoddington/multi-client
  - docker push kcoddington/multi-nginx
  - docker push kcoddington/multi-server
  - docker push kcoddington/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-843838715045"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
