version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      # sets the db password per the Docker Hub instructions
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: 'redis:latest'

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # puts a "lock" on /app/node_modules so it won't be copied over
      - /app/node_modules
      - ./server:/app
    environment:
      # the redis host here just refers to the redis service name we specified above
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      # name of postgres service above
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
    # puts a "lock" on /app/node_modules so it won't be copied over
    - /app/node_modules
    - ./client:/app

  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
    # puts a "lock" on /app/node_modules so it won't be copied over
    - /app/node_modules
    - ./worker:/app
